{% set version = "0.9.1" %}

package:
  name: composeml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/composeml/composeml-{{ version }}.tar.gz
  sha256: 62ac00bc7c12519001791787ded4c13147e3a5307422dc5112069849136769d5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pandas >=1.3.0
    - tqdm >=4.32.0
    - matplotlib-base >=3.3.3
    - seaborn >=0.11.0

test:
  commands:
    - pytest --pyargs composeml
  imports:
    - composeml
  requires:
    - pytest ==7.1.2
    - featuretools >=1.4.0
    - woodwork >=0.11.0
    - pyarrow >=3.0.0
  source_files:
    - composeml/*

about:
  doc_url: https://compose.alteryx.com
  dev_url: https://github.com/alteryx/compose
  home: https://compose.alteryx.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library for automated prediction engineering.

extra:
  recipe-maintainers:
    - gsheni
    - jeff-hernandez
    - rwedge
    - tamargrey
    - thehomebrewnerd
    - dvreed77
